test re-enable build with mixed running syntax

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,8 +19,6 @@ jobs:
         unity-version: [ 2019.4.36f1 ] #,2020.3.30f1, 2021.2.14f1
 
     steps:
-
-
       - name: Checkout Passthrough Example
         uses: actions/checkout@v2
         with:
@@ -35,6 +33,13 @@ jobs:
         run: |
           echo $UNITY_PATH 
           find $UNITY_PATH 
+          find /home/runner/Unity
+          echo $ANDROID_HOME
+          echo $ANDROID_NDK_HOME
+          echo $NDK_HOME
+      - name: accept licenses if not already done
+        run: |
+          echo "y" | /opt/Unity/${{ unity-version }}/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/tools/bin/sdkmanager --licenses
       - name: list all files in unity install dir
         run: |
           find /opt/Unity/
@@ -69,7 +74,32 @@ jobs:
       #  name: accept licenses
       #  command: |
       #    echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager --licenses
+      - name: manual license activation
+        run: |
+          /opt/Unity/${{ unity-version }}/Editor/Unity -quit -batchMode -logFile -noGraphics -manualLicenseFile license.alf || exit 0
+      - name: unity android build
+        run: |
+          /opt/Unity/${{ unity-version }}/Editor/Unity -quit -batchMode -logFile -noGraphics -executeMethod TestBuilder.Build || exit 0
+      #return license failed - "activated manually for this computer and can't be returned"  https://github.com/hardcoded2/WavePassthroughOverlayExample/runs/5540616684?check_suite_focus=true#step:9:79
+      #feels wrong not to do it... just ignore the error code i guess?
+      - name: return license
+        continue-on-error: true 
+        run: |
+          /opt/Unity/${{ unity-version }}/Editor/Unity -quit -batchMode -logFile -noGraphics -returnlicense || exit 0
 
       - name: list all files in build dir
         run: |
-          find .
+          find Builds/
+      - name: Archive production artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: builds
+          path: |
+            Builds/*.apk
+
+      - name: 'Upload Artifact'
+        uses: actions/upload-artifact@v2
+        with:
+          name: build${{ github.run_number }}
+          path: Builds/*apk
+      
